### ISSUE TITLE
Colorbar in Figure 3

### ISSUE THREAD

**Issue by luisortizuriarte** [JStiles9552/Assignment_3_CLIM_680#5]
Now that you've changed Figure 3 to reflect a different season under different NAO thresholds, you might also want to modify the colormap. Especially in the first panel, it appears that values extend beyond range of the colormap, leading to a very large green "blob". You can try increasing the range of values or specifying unique boundaries for the contourf plot.

**Comment by JStiles9552** [comment]
I have increased the ranges for all of the plots so they contain all the anomaly values. I am aware of the fact that some of colorbars go higher than the values in the anomalies. Unfortunately, the anomalies go much further from zero in the positive direction, meaning the positive anomalies have a higher threshold than the negative anomalies. This meant that the only way I could properly display the data was to have an equal threshold on both sides of zero that went as high as the maximum positive anomalies. I tried using an unequal threshold (starting at around -1.6 and ending at -2.4), but this lead to a colorbar that was not centered at zero and contours did not make sense as there were positive anomalies with brown (negative) coloring. Because of this, I had to use a threshold that went further than the maximum negative anomalies in order to properly center the colorbar.

**Comment by luisortizuriarte** [comment]
Thanks. You can see a lot more detail in those "positive" blobs that were in the previous one. It's also important to note that the positive values are much larger than the negative ones, which can get lost if the color scale is truncated. 

Closing this issue.
